version: '3.8'

services:
  # Service Discovery
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    # healthcheck:
      # Try a simpler health check - just check if port 8761 is listening
      # test: ["CMD", "curl", "-f", "http://localhost:8761"] 
      # interval: 30s
      # timeout: 10s
      # retries: 5
      # start_period: 40s  # Give it more time to start

    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 60s


  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Duc.2003  
      MYSQL_DATABASE: biometrics
    ports:
      - "3307:3306"  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pDuc.2003"]  
      interval: 30s
      timeout: 10s
      retries: 5

  # Access Control Service
  access-control-service:
    build: ./access-control-service
    container_name: access-control-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/access_control_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Duc.2003
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

  # Biometrics Service
  biometrics-service:
    build: ./biometrics-service
    container_name: biometrics-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/biometrics_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Duc.2003
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

  # Fingerprint Training Service
  # Fingerprint Training Service
  fingerprint-training:
    build: ./fingerprint_training
    container_name: fingerprint-training
    ports:
      - "8083:8083"
    volumes:
      - ./fingerprint_training:/app
    depends_on:
      discovery-server:
        condition: service_healthy

  # Model Management Service
  model-management-service:
    build: ./model-management-service
    container_name: model-management-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/model_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Duc.2003
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

  # Training Data Service
  training-data-service:
    build: ./training-data-service
    container_name: training-data-service
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/training_data_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Duc.2003
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

  # User Management Service
  user-management-service:
    build: ./user-management-service
    container_name: user-management-service
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Duc.2003
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_healthy
      mysql:
        condition: service_healthy

volumes:
  mysql-data: