version: '3.8'

services:
  api-gateway:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./api-gateway:/app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"

  access-control-service:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./access-control-service:/app
    command: mvn spring-boot:run
    ports:
      - "8081:8080"

  biometrics-service:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./biometrics-service:/app
    command: mvn spring-boot:run
    ports:
      - "8082:8080"

  model-management-service:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./model-management-service:/app
    command: mvn spring-boot:run
    ports:
      - "8083:8080"

  training-data-service:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./training-data-service:/app
    command: mvn spring-boot:run
    ports:
      - "8084:8080"

  user-management-service:
    image: maven:3.9.6-eclipse-temurin-17
    working_dir: /app
    volumes:
      - ./user-management-service:/app
    command: mvn spring-boot:run
    ports:
      - "8085:8080"
